services:
  folderr:
    build:
      context: .
    depends_on:
      - mongo
    volumes:
      - folderr:/usr/fldrr/Files
      - keys:/usr/fldrr/internal
  mongo:
    image: mongo
    restart: always
    volumes:
      - db-data:/data/mongodb
volumes:
  folderr:
  db-data:
  keys:
