services:
  folderr:
    build:
      context: .
      target: dev
      args:
        installtype: -D
        buildcmd: build
    depends_on:
      - db
    volumes:
      - folderr-images:/usr/fldrr/Files
    environment:
      NODE_ENV: dev
  db:
    image: mongo
    restart: always
    volumes:
      - db-data:/data/mongodb
volumes:
  db-data:
  folderr-images:
