/**
 * @fileoverview Codes to send in the response
 */

export interface FoldCodesI {
	fileParserError: number;
	noFile: number;
	noUpdate: number;
	fileMimeError: number;
	fileSizeLimit: number;
	fileForbiddenMime: number;
	fileDelete: number;
	fileUnknownError: number;
	noUserFound: number;
	noInput: number;
	partialInput: number;
	illegalInput: number;
	invalidPassword: number;
	illegalPassword: number;
	passwordSize: number;
	passwordError: number;
	usernameOrEmailTaken: number;
	illegalUsername: number;
	usernameSizeLimit: number;
	dbError: number;
	fatalLock: number;
	locked: number;
	shortUrlNotFound: number;
	shortUrlInvalid: number;
	shortUrlMissing: number;
	adminAdd: number;
	adminRemove: number;
	userDelete: number;
	userUpdate: number;
	userCreate: number;
	signupRequested: number;
	signupError: number;
	userDeniedAdmin: number;
	userDenied: number;
	UserAccepted: number;
	userAcceptedAdmin: number;
	tokenAdd: number;
	tokenSizeLimit: number;
	tokenRemove: number;
	tokensPurge: number;
	linkDelete: number;
	linkUnknownError: number;
	notificationDelete: number;
	notificationsPurge: number;
	evalError: number;
	evalSizeLimit: number;
	mirrorAdd: number;
	mirrorRemove: number;
	mirrorUnauthorized: number;
	mirrorInvalidUrl: number;
	mirrorReject: number;
	mirrorBannedUrl: number;
	unkownError: number;
	dbUnkownError: number;
	dbNotFound: number;
	permissionDeny: number;
	securityError: number;
	externalError: number;
	badEmail: number;
	emailerNotConfigured: number;
	bannedEmail: number;
	emailSent: number;
}

export const FoldCodes: FoldCodesI = {
	fileParserError: 1000,
	noFile: 1001,
	noUpdate: 1002,
	fileMimeError: 1003,
	fileSizeLimit: 1004,
	fileForbiddenMime: 1005,
	fileDelete: 1006,
	fileUnknownError: 1007,
	noUserFound: 1008,
	noInput: 1009,
	partialInput: 1010,
	illegalInput: 1011,
	invalidPassword: 1012,
	illegalPassword: 1013,
	passwordSize: 1014,
	passwordError: 1015,
	usernameOrEmailTaken: 1016,
	illegalUsername: 1017,
	usernameSizeLimit: 1018,
	dbError: 1019,
	fatalLock: 1020,
	locked: 1021,
	shortUrlNotFound: 1022,
	shortUrlInvalid: 1023,
	shortUrlMissing: 1024,
	adminAdd: 1025,
	adminRemove: 1026,
	userDelete: 1027,
	userUpdate: 1028,
	userCreate: 1029,
	signupRequested: 1030,
	signupError: 1031,
	userDeniedAdmin: 1032,
	userDenied: 1033,
	UserAccepted: 1034,
	userAcceptedAdmin: 1035,
	tokenAdd: 1036,
	tokenSizeLimit: 1037,
	tokenRemove: 1038,
	tokensPurge: 1039,
	linkDelete: 1040,
	linkUnknownError: 1041,
	notificationDelete: 1042,
	notificationsPurge: 1043,
	evalError: 1044,
	evalSizeLimit: 1045,
	mirrorAdd: 1046,
	mirrorRemove: 1047,
	mirrorUnauthorized: 1048,
	mirrorReject: 1049,
	mirrorInvalidUrl: 1050,
	mirrorBannedUrl: 1051,
	unkownError: 1052,
	dbUnkownError: 1053,
	dbNotFound: 1054,
	permissionDeny: 1055,
	securityError: 1056,
	externalError: 1057,
	badEmail: 1058,
	emailerNotConfigured: 1059,
	bannedEmail: 1060,
	emailSent: 1061
};
