// export { default as Home } from './Home';
export { default as Short } from './Short';
export { default as Images } from './Images';
export { default as Videos } from './Videos';
export { default as Files } from './Files';
// export { default as Login } from './Login';
// export { default as Logout } from './Logout';
// export { default as Signup } from './Signup';
// export { default as Shorten } from './Shorten';
// export { default as Account } from './Account';
// export { default as UploadImage } from './Upload_Image';
// export { default as Admin } from './Admin/Admin';
// export { default as Privacy } from './Privacy';
// export { default as Proceed } from './Proceed';
// export { default as Config } from './ConfigGen';
// export { default as AdminNotifications } from './Admin/Notifications';
// export { default as AdminVerification } from './Admin/Verification';
// export { default as AdminUsers } from './Admin/Users';
// export { default as OwnerManage } from './Owner/Manage';
export { default as APISignup } from './API/Signup';
export { default as APIPVerify } from './API/Verify_Acc';
export { default as APIDVerify } from './API/Deny_Acc';
export { default as APINotifs } from './API/Notifs';
export { default as APIDNotifs } from './API/Clear_Notifs';
export { default as APIDAccount } from './API/Delete_Account';
export { default as APIAccount } from './API/Account';
export { default as APIAdminNotify } from './API/Admin_Notification';
export { default as APIDNotify } from './API/Delete_Notify';
export { default as APIDAdminNotify } from './API/Delete_Admin_Notification';
export { default as APIUpdateAcc } from './API/Update_Account';
export { default as APIGenToken } from './API/GenToken';
export { default as APIShorten } from './API/Shorten';
export { default as APIDeleteLink } from './API/Delete_Link';
export { default as APILinks } from './API/Links';
export { default as APIUploadFile } from './API/Upload_File';
export { default as APIFiles } from './API/Files';
export { default as APIDeleteImage } from './API/Delete_File';
export { default as APILogin } from './API/Login';
export { default as APIUsers } from './API/Users';
export { default as APIInfo } from './API/Info';
export { default as APIOwnerManage } from './API/Manage';
export { default as APIPong } from './API/Pong';
export { default as APIConfigr } from './API/Configurator';
export { default as APIAVEXR } from './API/Add_Mirror';
export { default as APIDVEXR } from './API/Rm_Mirror';
export { default as APIEval } from './API/Eval';
export { default as Verify } from './Verify';
export { default as APIBan } from './API/Ban';
export { default as APIUnban } from './API/Unban';
export { default as APIWarn } from './API/Warn_User';
export { default as APITakedown } from './API/Takedown';
export { default as APILookup } from './API/Lookup_Content';
export { default as APIAccountLookup } from './API/Lookup_Account';
export { default as APITokens } from './API/Tokens';
export { default as APIDeleteToken } from './API/Delete_Token';
export { default as APIAddAdmin } from './API/Add_Admin';
export { default as APIDelAdmin } from './API/Del_Admin';
